default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: sax_academy_development

test:
  <<: *default
  database: sax_academy_test

production:
  <<: *default
  database: sax_academy_production
  host: <%= ENV['POSTGRES_HOST'] %>